TIMELINE_REFERENCE_SCORE = 40

COMMIT_REFERENCE_SCORE = 45

BODY_REFERENCE_SCORE = 35

COMMENT_REFERENCE_SCORE = 30

TITLE_SIMILARITY_SCORE = 25

LABEL_SIMILARITY_SCORE = 15

AUTHOR_SIMILARITY_SCORE = 10

DEFAULT_THRESHOLD = 60

CONFIDENCE_LEVELS = (
    (90, "Very High"),
    (70, "High"),
    (50, "Medium"),
    (30, "Low"),
    (0, "Very Low"),
)

MAX_STRONG_EVIDENCE_SCORE = 80

MAX_SUPPORTING_EVIDENCE_SCORE = 35

FILE_SIMILARITY_SCORE = 30

COMMIT_HISTORY_SIMILARITY_SCORE = 20
